overlay bootstrap, templates, lxd profiles

diff --git a/lxd-kube b/lxd-kube
--- a/lxd-kube
+++ b/lxd-kube
@@ -12,6 +12,30 @@ usage() {
     echo "Usage: lxd-kube [provision|destroyinstances|destroyprojects|verifyconfig]"
     exit 1
 }
+
+get_lxc_profile_path() {
+    if ! [ -f "$1" ]; then
+        echo "lxc/profiles/default/k8s.yaml"
+        return 0
+    fi
+    echo "$1"
+}
+get_kubernetes_bootstrap_path() {
+    if ! [ -f "$1" ]; then
+        echo "kubernetes/bootstrap/default/bootstrap.sh"
+        return 0
+    fi
+    echo "$1"
+}
+
+get_kubernetes_template_path() {
+    if [ -f "$1" ]; then
+        echo "$1"
+        return 0
+    fi
+    echo "kubernetes/templates/default/"$(basename "$1")
+}
+
 get_projects() {
     local fields
     local IFS=,
@@ -144,8 +168,10 @@ create_lxc_profiles() {
         else
             echo "#### [OK] Profile exists"
         fi
+
         echo "### Applying the settings in the '${values[1]}' profile in the '${values[0]}' LXC project."
-        lxc --project "${values[0]}" profile edit "${values[1]}" < <(cat lxc/profiles/"${values[1]}".yaml)
+
+        lxc --project "${values[0]}" profile edit "${values[1]}" < <(cat $(get_lxc_profile_path "lxc/profiles/"${values[0]}"/"${values[1]}".yaml"))
         if [ $? -eq 0 ]; then
             echo "#### [OK] Settings applied"
         else
@@ -344,10 +370,10 @@ provision_kubernetes_cluster() {
                 exit 255
             fi
 
-            TEMPLATE_DIR=kubernetes/templates
+            TEMPLATE_DIR=kubernetes/templates/"${values[0]}"
 
             echo "#### Installing the necessary software in the container, such as kubernetes, containerd and some dependent utilities."
-            echo "export K8S_VERSION=${values[8]}; $(cat 'kubernetes/bootstrap/install.sh')" | lxc --project "${values[0]}" exec "${values[2]}" -- bash >>kubernetes/logs/"${values[0]}"/"${values[2]}"/install.log 2>&1
+            echo "export K8S_VERSION=${values[8]}; $(cat $(get_kubernetes_bootstrap_path "kubernetes/bootstrap/"${values[0]}"/"${values[2]}"/bootstrap.sh"))" | lxc --project "${values[0]}" exec "${values[2]}" -- bash >>kubernetes/logs/"${values[0]}"/"${values[2]}"/install.log 2>&1
             if [ $? -eq 0 ]; then
                 echo "##### [OK] The required software has been installed"
             else
@@ -363,16 +389,13 @@ provision_kubernetes_cluster() {
             export K8S_POD_SUBNET=${values[7]}
             export K8S_VERSION=${values[8]}
 
-            echo "#### Processing the kubeadm-init-config.yaml template"
-            if ! [ -f ${TEMPLATE_DIR}/kubeadm-init-config.yaml ]; then
-                echo "##### [$?] Error, unable to find template kubeadm-init-config.yaml"
-                exit 255
-            fi
-            $(envsubst <${TEMPLATE_DIR}/kubeadm-init-config.yaml >${GENERATED_CONFIGS_DIR}/kubeadm-init-config.yaml) 2>>kubernetes/logs/"${values[0]}"/"${values[2]}"/install.log
+            kadminittemplate=$(get_kubernetes_template_path "${TEMPLATE_DIR}/kubeadm-init-config.yaml")
+            echo "#### Processing the ${kadminittemplate} template"
+            $(envsubst <"${kadminittemplate}" >${GENERATED_CONFIGS_DIR}/kubeadm-init-config.yaml) 2>>kubernetes/logs/"${values[0]}"/"${values[2]}"/install.log
             if [ $? -eq 0 ]; then
-                echo "##### [OK] The kubeadm-init-config.yaml template was processed successfully"
+                echo "##### [OK] The "${kadminittemplate}" template was processed successfully"
             else
-                echo "##### [$?] Error processing kubeadm-init-config.yaml template"
+                echo "##### [$?] Error processing "${kadminittemplate}" template"
                 exit 255
             fi
 
@@ -386,7 +409,7 @@ provision_kubernetes_cluster() {
             fi
 
             echo "#### Download the Kubernetes base images"
-            echo "kubeadm config images pull" | lxc --project "${values[0]}" exec "${values[2]}" -- bash >>kubernetes/logs/"${values[0]}"/"${values[2]}"/kubeadminit.log 2>&1
+            echo "kubeadm config images pull --kubernetes-version v${values[8]}" | lxc --project "${values[0]}" exec "${values[2]}" -- bash >>kubernetes/logs/"${values[0]}"/"${values[2]}"/kubeadminit.log 2>&1
             if [ $? -eq 0 ]; then
                 echo "##### [OK] The images were downloaded successfully"
             else
@@ -405,16 +428,13 @@ provision_kubernetes_cluster() {
 
             echo "mkdir -p /root/.kube; cp /etc/kubernetes/admin.conf /root/.kube/config; chown $(id -u):$(id -g) /root/.kube/config" | lxc --project "${values[0]}" exec "${values[2]}" -- bash
 
-            echo "#### Processing the kubeadm-flannel.yaml template"
-            if ! [ -f ${TEMPLATE_DIR}/kubeadm-init-config.yaml ]; then
-                echo "##### [$?] Error, unable to find template kubeadm-flannel.yaml"
-                exit 255
-            fi
-            $(envsubst <${TEMPLATE_DIR}/kubeadm-flannel.yaml >${GENERATED_CONFIGS_DIR}/kubeadm-flannel.yaml) 2>>kubernetes/logs/"${values[0]}"/"${values[2]}"/install.log
+            kadmflanneltemplate=$(get_kubernetes_template_path "${TEMPLATE_DIR}/kubeadm-flannel.yaml")
+            echo "#### Processing the ${kadmflanneltemplate} template"
+            $(envsubst <"${kadmflanneltemplate}" >${GENERATED_CONFIGS_DIR}/kubeadm-flannel.yaml) 2>>kubernetes/logs/"${values[0]}"/"${values[2]}"/install.log
             if [ $? -eq 0 ]; then
-                echo "##### [OK] The kubeadm-flannel.yaml template was processed successfully"
+                echo "##### [OK] The ${kadmflanneltemplate} template was processed successfully"
             else
-                echo "##### [$?] Error processing kubeadm-flannel.yaml template"
+                echo "##### [$?] Error processing ${kadmflanneltemplate} template"
                 exit 255
             fi
 
@@ -427,26 +447,24 @@ provision_kubernetes_cluster() {
                 exit 255
             fi
 
-            echo "#### Creating kubeconfig to access the master plane"
             export CA_CERT_HASH=$(echo "openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* /sha256:/'" | lxc --project "${values[0]}" exec "${values[2]}" -- bash)
             export CA_DATA_B64=$(echo "cat /etc/kubernetes/pki/ca.crt | base64 -w0" | lxc --project "${values[0]}" exec "${values[2]}" -- bash)
             export CLIENT_CERT_B64=$(echo "cat /etc/kubernetes/pki/apiserver-kubelet-client.crt | base64 -w0" | lxc --project "${values[0]}" exec "${values[2]}" -- bash)
             export CLIENT_KEY_B64=$(echo "cat /etc/kubernetes/pki/apiserver-kubelet-client.key | base64 -w0" | lxc --project "${values[0]}" exec "${values[2]}" -- bash)
-            envsubst <${TEMPLATE_DIR}/kubeadm-config.yaml >"${KUBECTL_CONFIGS_DIR}"/kubeconfig
+            kubeconfigtemplate=$(get_kubernetes_template_path "${TEMPLATE_DIR}/kubeadm-config.yaml")
+            echo "#### Processing the ${kubeconfigtemplate} to access the master plane"
+            echo "#### Creating "${KUBECTL_CONFIGS_DIR}"/kubeconfig to access the master plane"
+            envsubst <"${kubeconfigtemplate}" >"${KUBECTL_CONFIGS_DIR}"/kubeconfig
 
-            echo "#### Processing the kubeadm-join-config.yaml template to join workers"
-            if ! [ -f ${TEMPLATE_DIR}/kubeadm-init-config.yaml ]; then
-                echo "##### [$?] Error, unable to find template kubeadm-join-config.yaml"
-                exit 255
-            fi
-            $(envsubst <${TEMPLATE_DIR}/kubeadm-join-config.yaml >${GENERATED_CONFIGS_DIR}/kubeadm-join-config.yaml) 2>>kubernetes/logs/"${values[0]}"/"${values[2]}"/install.log
+            kadmjointemplate=$(get_kubernetes_template_path "${TEMPLATE_DIR}/kubeadm-join-config.yaml")
+            echo "#### Processing the ${kadmjointemplate} template to join workers"
+            $(envsubst <"${kadmjointemplate}" >${GENERATED_CONFIGS_DIR}/kubeadm-join-config.yaml) 2>>kubernetes/logs/"${values[0]}"/"${values[2]}"/install.log
             if [ $? -eq 0 ]; then
-                echo "##### [OK] The kubeadm-join-config.yaml template was processed successfully"
+                echo "##### [OK] The ${kadmjointemplate} template was processed successfully"
             else
-                echo "##### [$?] Error processing kubeadm-join-config.yaml template"
+                echo "##### [$?] Error processing ${kadmjointemplate} template"
                 exit 255
             fi
-
             echo "### END Configuring the master plane: ${values[2]}"
             echo
         fi
@@ -470,9 +488,9 @@ provision_kubernetes_cluster() {
                 echo "##### [$?] Error creating ddd directory for logs"
                 exit 255
             fi
-
+            
             echo "#### Installing the necessary software in the container, such as kubernetes, containerd and some dependent utilities."
-            echo "export K8S_VERSION=${values[8]}; $(cat 'kubernetes/bootstrap/install.sh')" | lxc --project "${values[0]}" exec "${values[2]}" bash >>kubernetes/logs/"${values[0]}"/"${values[2]}"/install.log 2>&1
+            echo "export K8S_VERSION=${values[8]}; $(cat $(get_kubernetes_bootstrap_path "kubernetes/bootstrap/"${values[0]}"/"${values[2]}"/bootstrap.sh"))" | lxc --project "${values[0]}" exec "${values[2]}" bash >>kubernetes/logs/"${values[0]}"/"${values[2]}"/install.log 2>&1
             if [ $? -eq 0 ]; then
                 echo "##### [OK] The required software has been installed"
             else
