add postboot script logic, clean

diff --git a/lxd-kube b/lxd-kube
--- a/lxd-kube
+++ b/lxd-kube
@@ -46,6 +46,13 @@ get_kubernetes_bootstrap_path() {
     fi
     echo "$1"
 }
+get_kubernetes_postboot_path() {
+    if ! [ -f "$1" ]; then
+        echo "kubernetes/postboot/default/postboot.sh"
+        return 0
+    fi
+    echo "$1"
+}
 
 get_kubernetes_template_path() {
     if [ -f "$1" ]; then
@@ -181,9 +188,6 @@ is_in_array() {
 lxc_stop_containers() {
     echo -e "\n## Stopping project instances...\n"
 
-    #local PROJECT_NAME=$(yq e '.config.lxd.projectName' "config/${CONFIG_FILE}")
-    #local INSTANCES_LENGTH=$(yq e '.config.instances | length' "config/${CONFIG_FILE}")
-
     for ((i = 0; i < ${INSTANCES_LENGTH}; i++)); do
         local INSTANCE_NAME=$(yq e ".config.instances[$i].lxd.name" "config/${CONFIG_FILE}")
 
@@ -204,9 +208,6 @@ lxc_stop_containers() {
 
 lxc_start_containers() {
     echo -e "\n## Starting project instances...\n"
-
-    #local PROJECT_NAME=$(yq e '.config.lxd.projectName' "config/${CONFIG_FILE}")
-    #local INSTANCES_LENGTH=$(yq e '.config.instances | length' "config/${CONFIG_FILE}")
 
     for ((i = 0; i < ${INSTANCES_LENGTH}; i++)); do
         local INSTANCE_NAME=$(yq e ".config.instances[$i].lxd.name" "config/${CONFIG_FILE}")
@@ -229,9 +230,6 @@ lxc_start_containers() {
 
 lxc_pause_containers() {
     echo -e "\n## Pausing project instances...\n"
-
-    #local PROJECT_NAME=$(yq e '.config.lxd.projectName' "config/${CONFIG_FILE}")
-    #local INSTANCES_LENGTH=$(yq e '.config.instances | length' "config/${CONFIG_FILE}")
 
     for ((i = 0; i < ${INSTANCES_LENGTH}; i++)); do
         local INSTANCE_NAME=$(yq e ".config.instances[$i].lxd.name" "config/${CONFIG_FILE}")
@@ -318,11 +316,7 @@ create_lxc_bridges() {
         echo "#### [OK] Bridge exists"
     fi
 
-    #K8S_API_ENDPOINT_DOMAIN="${K8S_API_ENDPOINT}"
-    #LXD_PROJECT="${PROJECT_NAME}"
-
     mkdir -p generated-configs/lxc/bridge/"${PROJECT_NAME}"
-    #$(envsubst <"lxc/lxdbridge/"${PROJECT_NAME}"/bridge.yaml" >generated-configs/lxc/bridge/"${PROJECT_NAME}"/bridge.yaml)
     evolve_templates "lxc/lxdbridge/${PROJECT_NAME}/bridge.yaml" "generated-configs/lxc/bridge/${PROJECT_NAME}/bridge.yaml"
     lxc --project "${PROJECT_NAME}" network edit "${PROJECT_NAME}"-br < <(cat generated-configs/lxc/bridge/"${PROJECT_NAME}"/bridge.yaml)
 
@@ -333,13 +327,9 @@ create_lxc_bridges() {
         exit $?
     fi
     echo
-    #fi
 }
 
 create_lxc_profiles() {
-
-    #local PROJECT_NAME=$(yq e '.config.lxd.projectName' "config/${CONFIG_FILE}")
-    #local INSTANCES_LENGTH=$(yq e '.config.instances | length' "config/${CONFIG_FILE}")
 
     for ((i = 0; i < ${INSTANCES_LENGTH}; i++)); do
         local PROFILE_NAME=$(yq e ".config.instances[$i].lxd.profile" "config/${CONFIG_FILE}")
@@ -361,10 +351,7 @@ create_lxc_profiles() {
         fi
 
         echo "### Applying the settings in the '${PROFILE_NAME}' profile in the '${PROJECT_NAME}' LXC project."
-        #export LXD_PROJECT="${PROJECT_NAME}"
-
         mkdir -p generated-configs/lxc/profiles/"${PROJECT_NAME}"
-        #$(envsubst <$(get_lxc_profile_path lxc/profiles/"${PROJECT_NAME}"/"${PROFILE_NAME}".yaml) >generated-configs/lxc/profiles/"${PROJECT_NAME}"/"${PROFILE_NAME}".yaml)
         evolve_templates $(get_lxc_profile_path "lxc/profiles/${PROJECT_NAME}/${PROFILE_NAME}.yaml") "generated-configs/lxc/profiles/${PROJECT_NAME}/${PROFILE_NAME}.yaml"
 
         lxc --project "${PROJECT_NAME}" profile edit "${PROFILE_NAME}" < <(cat generated-configs/lxc/profiles/"${PROJECT_NAME}"/"${PROFILE_NAME}".yaml)
@@ -379,8 +366,6 @@ create_lxc_profiles() {
 }
 
 create_lxc_instances() {
-    #local PROJECT_NAME=$(yq e '.config.lxd.projectName' "config/${CONFIG_FILE}")
-    #local INSTANCES_LENGTH=$(yq e '.config.instances | length' "config/${CONFIG_FILE}")
 
     local target=""
 
@@ -415,8 +400,6 @@ create_lxc_instances() {
 }
 
 delete_lxc_images() {
-    #local PROJECT_NAME=$(yq e '.config.lxd.projectName' "config/${CONFIG_FILE}")
-    #local INSTANCES_LENGTH=$(yq e '.config.instances | length' "config/${CONFIG_FILE}")
 
     echo "### Deleting images associated with the project"
 
@@ -443,8 +426,7 @@ delete_lxc_images() {
 }
 
 delete_lxc_bridges() {
-    #if ! is_cluster; then
-    #local PROJECT_NAME=$(yq e '.config.lxd.projectName' "config/${CONFIG_FILE}")
+
     if ! [ -f "lxc/lxdbridge/${PROJECT_NAME}/bridge.yaml" ]; then
         return
     fi
@@ -465,8 +447,6 @@ delete_lxc_bridges() {
 }
 
 delete_lxc_profiles() {
-    #local PROJECT_NAME=$(yq e '.config.lxd.projectName' "config/${CONFIG_FILE}")
-    #local INSTANCES_LENGTH=$(yq e '.config.instances | length' "config/${CONFIG_FILE}")
 
     for ((i = 0; i < ${INSTANCES_LENGTH}; i++)); do
         local PROFILE_NAME=$(yq e ".config.instances[$i].lxd.profile" "config/${CONFIG_FILE}")
@@ -504,9 +484,6 @@ delete_generated_files() {
 
 destroy() {
 
-    #local PROJECT_NAME=$(yq e '.config.lxd.projectName' "config/${CONFIG_FILE}")
-    #local INSTANCES_LENGTH=$(yq e '.config.instances | length' "config/${CONFIG_FILE}")
-
     echo -e "\n# Destroying LXD's '${PROJECT_NAME}' project...\n"
 
     destroyinstances
@@ -538,8 +515,6 @@ destroy() {
 }
 
 destroyinstances() {
-    #local PROJECT_NAME=$(yq e '.config.lxd.projectName' "config/${CONFIG_FILE}")
-    #local INSTANCES_LENGTH=$(yq e '.config.instances | length' "config/${CONFIG_FILE}")
 
     for ((i = 0; i < ${INSTANCES_LENGTH}; i++)); do
         local PROFILE_NAME=$(yq e ".config.instances[$i].lxd.profile" "config/${CONFIG_FILE}")
@@ -589,26 +564,31 @@ EOF
     cat $(get_kubernetes_bootstrap_path "kubernetes/bootstrap/"${PROJECT_NAME}"/"${INSTANCE_NAME}"/bootstrap.sh")
 }
 
+build_postboot_payload_content() {
+
+    cat <<EOF
+export PROJECT_NAME=${PROJECT_NAME};
+export INSTANCES_LENGTH=${INSTANCES_LENGTH};
+export K8S_VERSION=${K8S_VERSION};
+export K8S_API_ENDPOINT_DOMAIN=${K8S_API_ENDPOINT_DOMAIN};
+export K8S_CLUSTER_NAME=${K8S_CLUSTER_NAME};
+export K8S_POD_SUBNET=${K8S_POD_SUBNET};
+export PROJECT_PROFILES_NAME=${PROJECT_PROFILES_NAME};
+export PROJECT_INSTANCES_NAME=${PROJECT_INSTANCES_NAME};
+export PROJECT_INSTANCES_IMAGES=${PROJECT_INSTANCES_IMAGES};
+export PROJECT_INSTANCES_TYPE=${PROJECT_INSTANCES_TYPE};
+export CURRENT_INSTANCE_NAME=${CURRENT_INSTANCE_NAME};
+export CURRENT_INSTANCE_TYPE=${CURRENT_INSTANCE_TYPE};
+export CURRENT_PROFILE_NAME=${CURRENT_PROFILE_NAME};
+export CURRENT_INSTANCE_IMAGE=${CURRENT_INSTANCE_IMAGE};
+export CURRENT_INSTANCE_INDEX=${CURRENT_INSTANCE_INDEX};
+export CURRENT_INSTANCE_IP=${INSTANCE_IP};
+EOF
+
+    cat $(get_kubernetes_postboot_path "kubernetes/postboot/"${PROJECT_NAME}"/"${INSTANCE_NAME}"/postboot.sh")
+}
+
 evolve_templates() {
-    #export ESCUDO='$'
-    #     envsubst '${ESCUDO}
-    # ${PROJECT_NAME}
-    # ${INSTANCES_LENGTH}
-    # ${K8S_VERSION}
-    # ${K8S_API_ENDPOINT_DOMAIN}
-    # ${K8S_CLUSTER_NAME}
-    # ${K8S_POD_SUBNET}
-    # ${PROJECT_PROFILES_NAME}
-    # ${PROJECT_INSTANCES_NAME}
-    # ${PROJECT_INSTANCES_IMAGES}
-    # ${PROJECT_INSTANCES_TYPE}
-    # ${CURRENT_INSTANCE_NAME}
-    # ${CURRENT_INSTANCE_TYPE}
-    # ${CURRENT_PROFILE_NAME}
-    # ${CURRENT_INSTANCE_IMAGE}
-    # ${CURRENT_INSTANCE_INDEX}
-    # ${INSTANCE_IP}
-    #' <"$1" >"$2"
 
     sed \
         -e "s?\${CA_CERT_HASH}?${CA_CERT_HASH}?" \
@@ -642,89 +622,6 @@ generate_kubernetes_token() {
     echo $(printf '%s' $(echo "$RANDOM" | md5sum) | cut -c 1-6).$(printf '%s' $(echo "$RANDOM" | md5sum) | cut -c 1-16)
 }
 
-kubernetes_inicialization() {
-
-    local init_directory="kubernetes/templates/${PROJECT_NAME}/init"
-    local generated_init_directory="generated-configs/${init_directory}"
-    mkdir -p "${generated_init_directory}"
-
-    local IFS=$(echo -en "\n\b")
-    local templates=$(find "${init_directory}" -type f 2>/dev/null)
-    local templates_num=$(find "${init_directory}" -type f 2>/dev/null | wc -l)
-    # echo $templates_num
-
-    # if [ ${templates_num} -lt 1 ]; then
-    #     return 0
-    # fi
-
-    echo "#### Initializing the master plane..."
-
-    echo "##### Generating a token in Kubernetes"
-    #export KUBEADM_TOKEN=$(echo "kubeadm token generate" | lxc --project "${PROJECT_NAME}" exec "${INSTANCE_NAME}" -- bash) >>logs/"${PROJECT_NAME}"/"${INSTANCE_NAME}"/install.log 2>&1
-    KUBEADM_TOKEN=$(generate_kubernetes_token)
-
-    kadminittemplate=$(get_kubernetes_template_path "${init_directory}/kubeadm-init-config.yaml")
-    echo "##### Processing the ${kadminittemplate} template"
-    #$(envsubst <"${kadminittemplate}" >${GENERATED_CONFIGS_DIR}/kubeadm-init-config.yaml) >>logs/"${PROJECT_NAME}"/"${INSTANCE_NAME}"/install.log 2>&1
-    evolve_templates "${kadminittemplate}" "${generated_init_directory}/kubeadm-init-config.yaml"
-    if [ $? -eq 0 ]; then
-        echo "###### [OK] The "${kadminittemplate}" template was processed successfully"
-    else
-        echo "###### [$?] Error processing "${kadminittemplate}" template"
-        exit 255
-    fi
-
-    echo "##### Copying the '${generated_init_directory}/kubeadm-init-config.yaml' configuration file to ${INSTANCE_NAME}"
-    lxc --project "${PROJECT_NAME}" file push -p ${generated_init_directory}/kubeadm-init-config.yaml ${INSTANCE_NAME}/root/kubeadm-init-config.yaml --uid 0
-    if [ $? -eq 0 ]; then
-        echo "###### [OK] The '${generated_init_directory}/kubeadm-init-config.yaml' configuration file has been successfully copied to ${INSTANCE_NAME}"
-    else
-        echo "###### [$?] Error when copying '${generated_init_directory}/kubeadm-init-config.yaml' configuration file to ${INSTANCE_NAME}"
-        exit 255
-    fi
-
-    echo "##### Download the Kubernetes base images"
-    echo "kubeadm config images pull --kubernetes-version v${K8S_VERSION}" | lxc --project "${PROJECT_NAME}" exec "${INSTANCE_NAME}" -- bash >>logs/"${PROJECT_NAME}"/"${INSTANCE_NAME}"/kubeadminit.log 2>&1
-    if [ $? -eq 0 ]; then
-        echo "###### [OK] The images were downloaded successfully"
-    else
-        echo "###### [$?] Error when downloading images"
-        exit 255
-    fi
-
-    echo "##### Initializing the master plane"
-    lxc --project "${PROJECT_NAME}" exec "${INSTANCE_NAME}" -- kubeadm --v=5 init --ignore-preflight-errors=all --config /root/kubeadm-init-config.yaml >>logs/"${PROJECT_NAME}"/"${INSTANCE_NAME}"/kubeadminit.log 2>&1
-    if [ $? -eq 0 ]; then
-        echo "###### [OK] The master plane has been successfully initialized"
-    else
-        echo "###### [$?] Error initializing the master plane"
-        exit 255
-    fi
-
-    echo "mkdir -p /root/.kube; cp /etc/kubernetes/admin.conf /root/.kube/config; chown $(id -u):$(id -g) /root/.kube/config" | lxc --project "${PROJECT_NAME}" exec "${INSTANCE_NAME}" -- bash
-
-    CA_CERT_HASH=$(echo "openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* /sha256:/'" | lxc --project "${PROJECT_NAME}" exec "${INSTANCE_NAME}" -- bash)
-    CA_DATA_B64=$(echo "cat /etc/kubernetes/pki/ca.crt | base64 -w0" | lxc --project "${PROJECT_NAME}" exec "${INSTANCE_NAME}" -- bash)
-    CLIENT_CERT_B64=$(echo "cat /etc/kubernetes/pki/apiserver-kubelet-client.crt | base64 -w0" | lxc --project "${PROJECT_NAME}" exec "${INSTANCE_NAME}" -- bash)
-    CLIENT_KEY_B64=$(echo "cat /etc/kubernetes/pki/apiserver-kubelet-client.key | base64 -w0" | lxc --project "${PROJECT_NAME}" exec "${INSTANCE_NAME}" -- bash)
-
-    kubeconfigtemplate=$(get_kubernetes_template_path "kubernetes/templates/${PROJECT_NAME}/kubeconfig/kubeadm-config.yaml")
-    echo "#### Processing the ${kubeconfigtemplate} to access the master plane"
-    echo "#### Creating kubernetes/kubectl-configs/${PROJECT_NAME}/kubeconfig to access the master plane"
-    evolve_templates "${kubeconfigtemplate}" "${KUBECTL_CONFIGS_DIR}/kubeconfig"
-
-    kadmjointemplate=$(get_kubernetes_template_path "${TEMPLATE_DIR}/kubeadm-join-config.yaml")
-    echo "#### Processing the ${kadmjointemplate} template to join workers"
-    #$(envsubst <"${kadmjointemplate}" >${GENERATED_CONFIGS_DIR}/kubeadm-join-config.yaml) 2>>logs/"${PROJECT_NAME}"/"${INSTANCE_NAME}"/install.log
-    evolve_templates "${kadmjointemplate}" "${GENERATED_CONFIGS_DIR}/kubeadm-join-config.yaml"
-    if [ $? -eq 0 ]; then
-        echo "##### [OK] The ${kadmjointemplate} template was processed successfully"
-    else
-        echo "##### [$?] Error processing ${kadmjointemplate} template"
-        exit 255
-    fi
-}
-
 apply_cni_configs() {
 
     local cni_directory="kubernetes/templates/${PROJECT_NAME}/cni"
@@ -736,7 +633,6 @@ apply_cni_configs() {
     local IFS=$(echo -en "\n\b")
     local templates=$(find "${cni_directory}" -type f 2>/dev/null)
     local templates_num=$(find "${cni_directory}" -type f 2>/dev/null | wc -l)
-    #echo $templates_num
 
     if [ ${templates_num} -lt 1 ]; then
         return 0
@@ -745,8 +641,6 @@ apply_cni_configs() {
 
     for TEMPLATE in ${templates}; do
         local file_name=$(basename ${TEMPLATE})
-        # echo "source '$TEMPLATE'"
-        # echo "dest 'generated-configs/$TEMPLATE'"
 
         echo "##### Processing the ${file_name} template"
         evolve_templates "${TEMPLATE}" "generated-configs/${TEMPLATE}"
@@ -757,13 +651,6 @@ apply_cni_configs() {
 }
 
 provision_kubernetes_cluster() {
-
-    #local PROJECT_NAME=$(yq e '.config.lxd.projectName' "config/${CONFIG_FILE}")
-    #local INSTANCES_LENGTH=$(yq e '.config.instances | length' "config/${CONFIG_FILE}")
-    #local K8S_VERSION=$(yq e ".config.kubernetes.version" "config/${CONFIG_FILE}")
-    #local K8S_API_ENDPOINT=$(yq e '.config.kubernetes.controlPlaneEndpointDomain' "config/${CONFIG_FILE}")
-    #local K8S_CLUSTER_NAME=$(yq e '.config.kubernetes.clusterName' "config/${CONFIG_FILE}")
-    #local K8S_POD_SUBNET=$(yq e '.config.kubernetes.podSubnet' "config/${CONFIG_FILE}")
 
     for ((i = 0; i < ${INSTANCES_LENGTH}; i++)); do
         local PROFILE_NAME=$(yq e ".config.instances[$i].lxd.profile" "config/${CONFIG_FILE}")
@@ -783,11 +670,6 @@ provision_kubernetes_cluster() {
         if [ ${K8S_KUBE_CONFIG_ENDPOINT_USE_IP} = true ]; then
             K8S_API_ENDPOINT=${INSTANCE_IP}
         fi
-
-        #echo  $K8S_API_ENDPOINT
-        #exit
-        #apply_cni_configs
-        #exit
 
         if [[ "${INSTANCE_TYPE}" == "master" ]]; then
             K8S_MASTER_INSTANCE_NAME=${INSTANCE_NAME}
@@ -864,16 +746,12 @@ provision_kubernetes_cluster() {
                 exit 255
             fi
 
-            #exit
-            #kubernetes_inicialization
 
             echo "#### Generating a token in Kubernetes"
-            #export KUBEADM_TOKEN=$(echo "kubeadm token generate" | lxc --project "${PROJECT_NAME}" exec "${INSTANCE_NAME}" -- bash) >>logs/"${PROJECT_NAME}"/"${INSTANCE_NAME}"/install.log 2>&1
             KUBEADM_TOKEN=$(generate_kubernetes_token)
 
             kadminittemplate=$(get_kubernetes_template_path "${TEMPLATE_DIR}/init/kubeadm-init-config.yaml")
             echo "#### Processing the ${kadminittemplate} template"
-            #$(envsubst <"${kadminittemplate}" >${GENERATED_CONFIGS_DIR}/kubeadm-init-config.yaml) >>logs/"${PROJECT_NAME}"/"${INSTANCE_NAME}"/install.log 2>&1
             mkdir -p "${GENERATED_CONFIGS_DIR}/init/"
             evolve_templates "${kadminittemplate}" "${GENERATED_CONFIGS_DIR}/init/kubeadm-init-config.yaml"
             if [ $? -eq 0 ]; then
@@ -920,13 +798,11 @@ provision_kubernetes_cluster() {
             kubeconfigtemplate=$(get_kubernetes_template_path "${TEMPLATE_DIR}/kubeconfig/kubeadm-config.yaml")
             echo "#### Processing the ${kubeconfigtemplate} to access the master plane"
             echo "#### Creating ${KUBECTL_CONFIGS_DIR}/kubeconfig to access the master plane"
-            #envsubst <"${kubeconfigtemplate}" >"${KUBECTL_CONFIGS_DIR}"/kubeconfig
             evolve_templates "${kubeconfigtemplate}" "${KUBECTL_CONFIGS_DIR}/kubeconfig"
 
             mkdir -p "${GENERATED_CONFIGS_DIR}/join/"
             kadmjointemplate=$(get_kubernetes_template_path "${TEMPLATE_DIR}/join/kubeadm-join-config.yaml")
             echo "#### Processing the ${kadmjointemplate} template to join workers"
-            #$(envsubst <"${kadmjointemplate}" >${GENERATED_CONFIGS_DIR}/kubeadm-join-config.yaml) 2>>logs/"${PROJECT_NAME}"/"${INSTANCE_NAME}"/install.log
             evolve_templates "${kadmjointemplate}" "${GENERATED_CONFIGS_DIR}/join/kubeadm-join-config.yaml"
             if [ $? -eq 0 ]; then
                 echo "##### [OK] The ${kadmjointemplate} template was processed successfully"
@@ -983,7 +859,6 @@ provision_kubernetes_cluster() {
             fi
 
             echo "#### Installing the necessary software in the container, such as kubernetes, containerd and some dependent utilities."
-            #echo "export K8S_VERSION=${K8S_VERSION}; $(cat $(get_kubernetes_bootstrap_path "kubernetes/bootstrap/"${PROJECT_NAME}"/"${INSTANCE_NAME}"/bootstrap.sh"))" | lxc --project "${PROJECT_NAME}" exec "${INSTANCE_NAME}" bash >>logs/"${PROJECT_NAME}"/"${INSTANCE_NAME}"/install.log 2>&1
             build_bootstrap_payload_content "${PROJECT_NAME}" "${INSTANCE_NAME}" | lxc --project "${PROJECT_NAME}" exec "${INSTANCE_NAME}" -- bash >>logs/"${PROJECT_NAME}"/"${INSTANCE_NAME}"/install.log 2>&1
             if [ $? -eq 0 ]; then
                 echo "##### [OK] The required software has been installed"
@@ -991,7 +866,7 @@ provision_kubernetes_cluster() {
                 echo "##### [$?] Errors appeared when installing the necessary software"
                 exit 255
             fi
-            #exit
+
             GENERATED_CONFIGS_DIR="generated-configs/kubernetes/templates/${PROJECT_NAME}/join"
 
             echo "#### Copying the '${GENERATED_CONFIGS_DIR}/kubeadm-join-config.yaml' configuration file to ${INSTANCE_NAME}"
@@ -1018,8 +893,6 @@ provision_kubernetes_cluster() {
 }
 
 copysshkey() {
-    #local PROJECT_NAME=$(yq e '.config.lxd.projectName' "config/${CONFIG_FILE}")
-    #local INSTANCES_LENGTH=$(yq e '.config.instances | length' "config/${CONFIG_FILE}")
 
     for ((i = 0; i < ${INSTANCES_LENGTH}; i++)); do
         local PROFILE_NAME=$(yq e ".config.instances[$i].lxd.profile" "config/${CONFIG_FILE}")
@@ -1067,9 +940,22 @@ provision() {
 
     provision_kubernetes_cluster
 
+    # This script will run after basic kubernetes boots. With it we can install
+    # and configure one or many applications for a given project. Using the
+    # kubeconfig generated during kubernetes cluster initialization.
+    echo "#### Running the post boot script in project ${PROJECT_NAME}..."
+    build_postboot_payload_content | bash >>logs/"${PROJECT_NAME}"/"${INSTANCE_NAME}"/postboot.log 2>&1
+    if [ $? -eq 0 ]; then
+        echo "##### [OK] The postboot script ran without problems."
+    else
+        echo "##### [$?] An error status was returned when running the postboot script."
+        exit 255
+    fi
+    
+
     echo -e "## END of Kubernetes cluster provisioning"
     echo -e "\n# END Provisioning Kubernetes Cluster inside LXC containers\n"
-    
+
 }
 
 valid_config() {
@@ -1081,7 +967,6 @@ valid_config() {
     else
         K8S_KUBE_CONFIG_ENDPOINT_USE_IP=true
     fi
-
 
     PROJECT_TARGET=$(yq e '.config.lxd.target' "config/${CONFIG_FILE}")
     if [ "x${PROJECT_TARGET}" = "xnull" ]; then
